version: '3.9'
services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    volumes:
      - .:/src
      - ./node_modules:/src/node_modules
    working_dir: /src
    env_file: .env.example
    image: node:12-alpine
    command: yarn start
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      database:
        condition: service_healthy
